// ==========================================
//  CONDO AD AUTOMATION — CONFIG
//  แก้ไขข้อมูลนี้ก่อนรัน script
// ==========================================

module.exports = {

  // ---- ข้อมูลเจ้าของ ----
  owner: {
    name: 'ณรงค์ (พี่ม่ำ)',
    phone: '081-8327707',
    lineId: 'narong.t',
    email: 'mumkoy@gmail.com',
  },

  // ---- Login credentials (ใส่ของจริงก่อนรัน) ----
  credentials: {
    livinginsider: { email: 'YOUR_EMAIL', password: 'YOUR_PASSWORD' },
    ddproperty:    { email: 'YOUR_EMAIL', password: 'YOUR_PASSWORD' },
    hipflat:       { email: 'YOUR_EMAIL', password: 'YOUR_PASSWORD' },
    fazwaz:        { email: 'YOUR_EMAIL', password: 'YOUR_PASSWORD' },
    facebook:      { email: 'YOUR_EMAIL', password: 'YOUR_PASSWORD' },
  },

  // ---- Puppeteer settings ----
  puppeteer: {
    headless: false,        // true = รันเงียบๆ | false = เห็นหน้าจอ
    slowMo: 80,             // ms หน่วงระหว่าง action (ป้องกัน bot detection)
    timeout: 30000,
    screenshotOnError: true,
  },

  // ---- ห้องทั้ง 6 หน่วย ----
  units: [
    {
      id: 1,
      project: 'Amari Residences Hua Hin',
      type: '2 ห้องนอน 2 ห้องน้ำ',
      typeEN: '2 Bedroom 2 Bathroom',
      floor: 7,
      size: 83,
      rent: 40000,
      unitNo: '107/191',
      location: 'หัวหิน, ประจวบคีรีขันธ์',
      locationEN: 'Hua Hin, Prachuap Khiri Khan',
      nearBTS: false,
      nearMRT: false,
      nearARL: false,
      highlights: ['วิวทะเล', 'โครงการ 5 ดาว', 'ตกแต่งพร้อมอยู่', 'สระว่ายน้ำ', 'ฟิตเนส'],
      highlightsEN: ['Sea view', '5-star branded residence', 'Fully furnished', 'Swimming pool', 'Fitness'],
      descTH: 'ให้เช่า คอนโด Amari Residences Hua Hin 2 ห้องนอน 2 ห้องน้ำ ชั้น 7 ทิศใต้ วิวทะเล ขนาด 83 ตร.ม. ค่าเช่า 40,000 บาท/เดือน โครงการระดับ 5 ดาวภายใต้แบรนด์ Amari Hotel ตกแต่งพร้อมอยู่ เฟอร์นิเจอร์+เครื่องใช้ไฟฟ้าครบ สระว่ายน้ำ ฟิตเนส ใกล้ Market Village และชายหาดหัวหิน ติดต่อ 081-8327707 Line: narong.t',
      descEN: 'FOR RENT: Amari Residences Hua Hin — 2 Bed 2 Bath, 7th Floor South-facing Sea View, 83 sqm. THB 40,000/month. Prestigious 5-star branded residence under Amari Hotel. Fully furnished & equipped. Pool, fitness, concierge. Near Market Village & Hua Hin beach. Contact: 081-8327707 Line: narong.t',
      photoDir: 'https://drive.google.com/drive/folders/1blofgG7nT07ZxehSH6M4kb25Qybw8cWi',
    },
    {
      id: 2,
      project: 'Ideo Mobi Bangsue',
      type: '2 ห้องนอน 2 ห้องน้ำ',
      typeEN: '2 Bedroom 2 Bathroom',
      floor: 29,
      size: 47.5,
      rent: 29000,
      unitNo: '5/584',
      location: 'บางซื่อ, กรุงเทพฯ',
      locationEN: 'Bang Sue, Bangkok',
      nearBTS: false,
      nearMRT: true,
      nearARL: true,
      highlights: ['ชั้น 29 วิวพาโนรามา', 'ใกล้ MRT บางซื่อ', 'สถานีกลางกรุงเทพ', 'สระว่ายน้ำ', 'Co-working'],
      highlightsEN: ['29th floor panoramic view', 'Steps from MRT Bang Sue', 'Krung Thep Aphiwat Station', 'Pool', 'Co-working'],
      descTH: 'ให้เช่า คอนโด Ideo Mobi Bangsue 2 ห้องนอน 2 ห้องน้ำ ชั้น 29 วิวพาโนรามากรุงเทพฯ ขนาด 47.5 ตร.ม. ค่าเช่า 29,000 บาท/เดือน ใกล้ MRT บางซื่อ/สถานีกลางกรุงเทพ (Krung Thep Aphiwat) ต่อ MRT/ARL/รถไฟสะดวกมาก สระว่ายน้ำ ฟิตเนส Co-working ติดต่อ 081-8327707 Line: narong.t',
      descEN: 'FOR RENT: Ideo Mobi Bangsue — 2 Bed 2 Bath, 29th Floor Panoramic Bangkok View, 47.5 sqm. THB 29,000/month. Steps from MRT Bang Sue & Krung Thep Aphiwat Central Station. Pool, fitness, co-working. Ideal for professionals & expats. Contact: 081-8327707 Line: narong.t',
      photoDir: 'https://drive.google.com/drive/folders/1_T7ufVZP155AER5htAfrNqPqZjvCoPBA',
    },
    {
      id: 3,
      project: 'KnightsBridge Prime Sathorn',
      type: '1 ห้องนอน Duplex',
      typeEN: '1 Bedroom Duplex',
      floor: 27,
      size: 44,
      rent: 39000,
      unitNo: '599/332',
      location: 'สาทร, กรุงเทพฯ',
      locationEN: 'Sathorn, Bangkok',
      nearBTS: true,
      nearMRT: false,
      nearARL: false,
      highlights: ['Duplex 2 ชั้น', 'ชั้น 27 วิวเมือง', 'ย่าน Sathorn CBD', 'ใกล้ BTS Chong Nonsi', 'ใกล้ BNH Hospital'],
      highlightsEN: ['2-level duplex', 'Floor 27 city view', 'Sathorn CBD', 'Near BTS Chong Nonsi', 'Near BNH Hospital'],
      descTH: 'ให้เช่า คอนโด KnightsBridge Prime Sathorn 1 ห้องนอน Duplex 2 ชั้น ชั้น 27 วิวกรุงเทพฯ ยามค่ำคืน รวม 44 ตร.ม. (30.5+13.5) ค่าเช่า 39,000 บาท/เดือน ทำเล Sathorn ย่านธุรกิจชั้นนำ ใกล้ BTS Chong Nonsi/Saint Louis โรงพยาบาล BNH ติดต่อ 081-8327707 Line: narong.t',
      descEN: 'FOR RENT: KnightsBridge Prime Sathorn — 1 Bed Duplex, Floor 27, 44 sqm total. THB 39,000/month. Sathorn CBD. Near BTS Chong Nonsi, BNH Hospital, Silom dining. Stunning Bangkok night skyline. Contact: 081-8327707 Line: narong.t',
      photoDir: 'https://drive.google.com/drive/folders/15xWSMpMQydrnlwOIX26myb9tZKL1ZAIo',
    },
    {
      id: 4,
      project: 'Park Origin Chula-Samyan',
      type: '1 ห้องนอน Duplex',
      typeEN: '1 Bedroom Duplex',
      floor: 27,
      size: 24,
      rent: 39000,
      unitNo: '168/247',
      location: 'จุฬา-สามย่าน, กรุงเทพฯ',
      locationEN: 'Chula-Samyan, Bangkok',
      nearBTS: false,
      nearMRT: true,
      nearARL: false,
      highlights: ['⭐ Highlight', 'Duplex ชั้น 27', 'MRT สามย่าน 2 นาที', 'ใกล้จุฬาฯ', 'สามย่านมิตรทาวน์'],
      highlightsEN: ['⭐ Top Pick', 'Duplex Floor 27', 'MRT Sam Yan 2 min', 'Near Chula University', 'Samyan Mitrtown'],
      descTH: 'ให้เช่า คอนโด Park Origin Chula-Samyan 1 ห้องนอน Duplex ชั้น 27 วิวสวนจุฬาฯ 24 ตร.ม. ค่าเช่า 39,000 บาท/เดือน เดิน 2 นาทีถึง MRT สามย่าน ใกล้จุฬาลงกรณ์มหาวิทยาลัย โรงพยาบาลจุฬาฯ สามย่านมิตรทาวน์ เหมาะแพทย์ นักวิชาการ ชาวต่างชาติ ติดต่อ 081-8327707 Line: narong.t',
      descEN: 'FOR RENT: Park Origin Chula-Samyan ⭐ — 1 Bed Duplex, Floor 27 above Chula park, 24 sqm. THB 39,000/month. 2-min walk MRT Sam Yan. Near Chulalongkorn University, King Chulalongkorn Memorial Hospital, Samyan Mitrtown. Contact: 081-8327707 Line: narong.t',
      photoDir: 'https://drive.google.com/drive/folders/1qiyIL1XjceGFwN-kOHWCV8cV5zSV01ct',
    },
    {
      id: 5,
      project: 'Quattro Thonglor Soi 4',
      type: '1 ห้องนอน 1 ห้องน้ำ',
      typeEN: '1 Bedroom 1 Bathroom',
      floor: 11,
      size: 63,
      rent: 57000,
      unitNo: '134/82',
      location: 'ทองหล่อ, กรุงเทพฯ',
      locationEN: 'Thonglor, Bangkok',
      nearBTS: true,
      nearMRT: false,
      nearARL: false,
      highlights: ['ห้องใหญ่ 63 ตร.ม.', 'ชั้น 11', 'ย่านทองหล่อ', 'BTS ทองหล่อ 5 นาที', 'ใกล้ Samitivej'],
      highlightsEN: ['Huge 63 sqm', 'Floor 11', 'Thonglor neighborhood', '5-min BTS Thong Lo', 'Near Samitivej Hospital'],
      descTH: 'ให้เช่า คอนโด Quattro Thonglor Soi 4 1 ห้องนอน 1 ห้องน้ำ ชั้น 11 ห้องใหญ่มาก 63 ตร.ม. ค่าเช่า 57,000 บาท/เดือน ย่านทองหล่อ 5 นาทีจาก BTS ทองหล่อ ใกล้โรงพยาบาล Samitivej เหมาะ Expat ครอบครัว อยู่ระยะยาว ติดต่อ 081-8327707 Line: narong.t',
      descEN: 'FOR RENT: Quattro Thonglor Soi 4 — 1 Bed 1 Bath, Floor 11, Very Large 63 sqm. THB 57,000/month. Thonglor area. 5-min walk BTS Thong Lo. Near Samitivej Hospital. Perfect for expats & long-term residents. Contact: 081-8327707 Line: narong.t',
      photoDir: 'https://drive.google.com/drive/folders/1GijLrVqKJGgize6xVlVIaBEQTuIK_MYR',
    },
    {
      id: 6,
      project: 'XT Phayathai',
      type: '1 ห้องนอน 1 ห้องน้ำ',
      typeEN: '1 Bedroom 1 Bathroom',
      floor: 14,
      size: 42,
      rent: 20000,
      unitNo: '515/1090',
      location: 'พญาไท, กรุงเทพฯ',
      locationEN: 'Phaya Thai, Bangkok',
      nearBTS: true,
      nearMRT: false,
      nearARL: true,
      highlights: ['ราคาดีที่สุด!', 'ชั้น 14', 'BTS พญาไท', 'Airport Rail Link', 'ใกล้สนามบิน'],
      highlightsEN: ['Best Value!', 'Floor 14', 'BTS Phaya Thai', 'Airport Rail Link', 'Direct to Suvarnabhumi'],
      descTH: 'ให้เช่า คอนโด XT Phayathai 1 ห้องนอน 1 ห้องน้ำ ชั้น 14 ขนาด 42 ตร.ม. ราคาดีที่สุด! เพียง 20,000 บาท/เดือน ใกล้ BTS พญาไท + ARL ไปสนามบินสุวรรณภูมิ เดินทางสะดวกมาก ใกล้วิคตอรี่มอนูเมนต์ สุขุมวิท ติดต่อ 081-8327707 Line: narong.t',
      descEN: 'FOR RENT: XT Phayathai — 1 Bed 1 Bath, Floor 14, 42 sqm. Only THB 20,000/month — BEST VALUE! Steps from BTS Phaya Thai & Airport Rail Link to Suvarnabhumi. Near Victory Monument & Sukhumvit. Contact: 081-8327707 Line: narong.t',
      photoDir: 'https://drive.google.com/drive/u/0/folders/1SqPYdBfsUv8dZ28-5fQ09ZMJeShWAgm2',
    },
  ],
};
